// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'NuxtLoadingBar': typeof import("../components/NuxtLoadingBar.vue")['default'],
    'TheFooter': typeof import("../components/TheFooter.vue")['default'],
    'TheHeader': typeof import("../components/TheHeader.vue")['default'],
    'TheHome': typeof import("../components/TheHome.vue")['default'],
    'TheMangaDetail': typeof import("../components/TheMangaDetail.vue")['default'],
    'TheNav': typeof import("../components/TheNav.vue")['default'],
    'TheRead': typeof import("../components/TheRead.vue")['default'],
    'TheSidebar': typeof import("../components/TheSidebar.vue")['default'],
    'VisitedComic': typeof import("../components/VisitedComic.vue")['default'],
    'CategorysCateList': typeof import("../components/categorys/CateList.vue")['default'],
    'CategorysComicItem': typeof import("../components/categorys/ComicItem.vue")['default'],
    'CommonPageLoading': typeof import("../components/common/PageLoading.vue")['default'],
    'CommonSearchLoading': typeof import("../components/common/SearchLoading.vue")['default'],
    'HomePageCatelog': typeof import("../components/home-page/Catelog.vue")['default'],
    'HomePageFavoriteStory': typeof import("../components/home-page/FavoriteStory.vue")['default'],
    'HomePageMangaUpdated': typeof import("../components/home-page/MangaUpdated.vue")['default'],
    'HomePageMaybeLove': typeof import("../components/home-page/MaybeLove.vue")['default'],
    'HomePageNewFeed': typeof import("../components/home-page/NewFeed.vue")['default'],
    'HomePageNewStory': typeof import("../components/home-page/NewStory.vue")['default'],
    'HomePageRankList': typeof import("../components/home-page/RankList.vue")['default'],
    'FilterByChapter': typeof import("../components/filter/ByChapter.vue")['default'],
    'FilterByComics': typeof import("../components/filter/ByComics.vue")['default'],
    'FilterByGender': typeof import("../components/filter/ByGender.vue")['default'],
    'FilterByGenres': typeof import("../components/filter/ByGenres.vue")['default'],
    'FilterByRank': typeof import("../components/filter/ByRank.vue")['default'],
    'FilterByStatus': typeof import("../components/filter/ByStatus.vue")['default'],
    'FilterListGenres': typeof import("../components/filter/ListGenres.vue")['default'],
    'MangaChaplist': typeof import("../components/manga/Chaplist.vue")['default'],
    'MangaChapterImg': typeof import("../components/manga/ChapterImg.vue")['default'],
    'MangaReadMangaFooter': typeof import("../components/manga/ReadMangaFooter.vue")['default'],
    'MangaReview': typeof import("../components/manga/Review.vue")['default'],
    'MangaDetailFollowButton': typeof import("../components/manga-detail/FollowButton.vue")['default'],
    'MangaDetailReadButton': typeof import("../components/manga-detail/ReadButton.vue")['default'],
    'MangaDetailReview': typeof import("../components/manga-detail/Review.vue")['default'],
    'ModalMangaSearch': typeof import("../components/modal/MangaSearch.vue")['default'],
    'ModalSearchResult': typeof import("../components/modal/SearchResult.vue")['default'],
    'PulseFavoriteStoryLoading': typeof import("../components/pulse/FavoriteStoryLoading.vue")['default'],
    'PulseMangaUpdatedLoading': typeof import("../components/pulse/MangaUpdatedLoading.vue")['default'],
    'PulseMaybeLoveLoading': typeof import("../components/pulse/MaybeLoveLoading.vue")['default'],
    'PulseVisitedComic': typeof import("../components/pulse/VisitedComic.vue")['default'],
    'SectionRankList': typeof import("../components/section/RankList.vue")['default'],
    'SectionSpotlight': typeof import("../components/section/Spotlight.vue")['default'],
    'SectionSpotlightBannerLoading': typeof import("../components/section/SpotlightBannerLoading.vue")['default'],
    'SectionSuggestion': typeof import("../components/section/Suggestion.vue")['default'],
    'SectionSwiperBannerLoading': typeof import("../components/section/SwiperBannerLoading.vue")['default'],
    'SectionSwiperCard': typeof import("../components/section/SwiperCard.vue")['default'],
    'SectionSwiperCardButton': typeof import("../components/section/SwiperCardButton.vue")['default'],
    'SectionSwiperItemLoading': typeof import("../components/section/SwiperItemLoading.vue")['default'],
    'SharedBannerBar': typeof import("../components/shared/BannerBar.vue")['default'],
    'SharedImg': typeof import("../components/shared/Img.vue")['default'],
    'SharedNewFeedLeftContent': typeof import("../components/shared/NewFeedLeftContent.vue")['default'],
    'SharedNewFeedRightContent': typeof import("../components/shared/NewFeedRightContent.vue")['default'],
    'SharedSwiperContent': typeof import("../components/shared/SwiperContent.vue")['default'],
    'SvgBack': typeof import("../components/svg/Back.vue")['default'],
    'SvgBannerTrending': typeof import("../components/svg/BannerTrending.vue")['default'],
    'SvgComment': typeof import("../components/svg/Comment.vue")['default'],
    'SvgHeaderFilterBack': typeof import("../components/svg/HeaderFilterBack.vue")['default'],
    'SvgNotify': typeof import("../components/svg/Notify.vue")['default'],
    'SvgSearch': typeof import("../components/svg/Search.vue")['default'],
    'SvgSearchFilterHeader': typeof import("../components/svg/SearchFilterHeader.vue")['default'],
    'SvgSmile': typeof import("../components/svg/Smile.vue")['default'],
    'SvgStar': typeof import("../components/svg/Star.vue")['default'],
    'SvgView': typeof import("../components/svg/View.vue")['default'],
    'SvgViewChapter': typeof import("../components/svg/ViewChapter.vue")['default'],
    'SvgViewSpotLight': typeof import("../components/svg/ViewSpotLight.vue")['default'],
    'SvgFollow': typeof import("../components/svg/follow.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default'],
    'NuxtImg': typeof import("../node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-img.vue")['default'],
    'NuxtPicture': typeof import("../node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-picture.vue")['default']
    'LazyNuxtLoadingBar': typeof import("../components/NuxtLoadingBar.vue")['default'],
    'LazyTheFooter': typeof import("../components/TheFooter.vue")['default'],
    'LazyTheHeader': typeof import("../components/TheHeader.vue")['default'],
    'LazyTheHome': typeof import("../components/TheHome.vue")['default'],
    'LazyTheMangaDetail': typeof import("../components/TheMangaDetail.vue")['default'],
    'LazyTheNav': typeof import("../components/TheNav.vue")['default'],
    'LazyTheRead': typeof import("../components/TheRead.vue")['default'],
    'LazyTheSidebar': typeof import("../components/TheSidebar.vue")['default'],
    'LazyVisitedComic': typeof import("../components/VisitedComic.vue")['default'],
    'LazyCategorysCateList': typeof import("../components/categorys/CateList.vue")['default'],
    'LazyCategorysComicItem': typeof import("../components/categorys/ComicItem.vue")['default'],
    'LazyCommonPageLoading': typeof import("../components/common/PageLoading.vue")['default'],
    'LazyCommonSearchLoading': typeof import("../components/common/SearchLoading.vue")['default'],
    'LazyHomePageCatelog': typeof import("../components/home-page/Catelog.vue")['default'],
    'LazyHomePageFavoriteStory': typeof import("../components/home-page/FavoriteStory.vue")['default'],
    'LazyHomePageMangaUpdated': typeof import("../components/home-page/MangaUpdated.vue")['default'],
    'LazyHomePageMaybeLove': typeof import("../components/home-page/MaybeLove.vue")['default'],
    'LazyHomePageNewFeed': typeof import("../components/home-page/NewFeed.vue")['default'],
    'LazyHomePageNewStory': typeof import("../components/home-page/NewStory.vue")['default'],
    'LazyHomePageRankList': typeof import("../components/home-page/RankList.vue")['default'],
    'LazyFilterByChapter': typeof import("../components/filter/ByChapter.vue")['default'],
    'LazyFilterByComics': typeof import("../components/filter/ByComics.vue")['default'],
    'LazyFilterByGender': typeof import("../components/filter/ByGender.vue")['default'],
    'LazyFilterByGenres': typeof import("../components/filter/ByGenres.vue")['default'],
    'LazyFilterByRank': typeof import("../components/filter/ByRank.vue")['default'],
    'LazyFilterByStatus': typeof import("../components/filter/ByStatus.vue")['default'],
    'LazyFilterListGenres': typeof import("../components/filter/ListGenres.vue")['default'],
    'LazyMangaChaplist': typeof import("../components/manga/Chaplist.vue")['default'],
    'LazyMangaChapterImg': typeof import("../components/manga/ChapterImg.vue")['default'],
    'LazyMangaReadMangaFooter': typeof import("../components/manga/ReadMangaFooter.vue")['default'],
    'LazyMangaReview': typeof import("../components/manga/Review.vue")['default'],
    'LazyMangaDetailFollowButton': typeof import("../components/manga-detail/FollowButton.vue")['default'],
    'LazyMangaDetailReadButton': typeof import("../components/manga-detail/ReadButton.vue")['default'],
    'LazyMangaDetailReview': typeof import("../components/manga-detail/Review.vue")['default'],
    'LazyModalMangaSearch': typeof import("../components/modal/MangaSearch.vue")['default'],
    'LazyModalSearchResult': typeof import("../components/modal/SearchResult.vue")['default'],
    'LazyPulseFavoriteStoryLoading': typeof import("../components/pulse/FavoriteStoryLoading.vue")['default'],
    'LazyPulseMangaUpdatedLoading': typeof import("../components/pulse/MangaUpdatedLoading.vue")['default'],
    'LazyPulseMaybeLoveLoading': typeof import("../components/pulse/MaybeLoveLoading.vue")['default'],
    'LazyPulseVisitedComic': typeof import("../components/pulse/VisitedComic.vue")['default'],
    'LazySectionRankList': typeof import("../components/section/RankList.vue")['default'],
    'LazySectionSpotlight': typeof import("../components/section/Spotlight.vue")['default'],
    'LazySectionSpotlightBannerLoading': typeof import("../components/section/SpotlightBannerLoading.vue")['default'],
    'LazySectionSuggestion': typeof import("../components/section/Suggestion.vue")['default'],
    'LazySectionSwiperBannerLoading': typeof import("../components/section/SwiperBannerLoading.vue")['default'],
    'LazySectionSwiperCard': typeof import("../components/section/SwiperCard.vue")['default'],
    'LazySectionSwiperCardButton': typeof import("../components/section/SwiperCardButton.vue")['default'],
    'LazySectionSwiperItemLoading': typeof import("../components/section/SwiperItemLoading.vue")['default'],
    'LazySharedBannerBar': typeof import("../components/shared/BannerBar.vue")['default'],
    'LazySharedImg': typeof import("../components/shared/Img.vue")['default'],
    'LazySharedNewFeedLeftContent': typeof import("../components/shared/NewFeedLeftContent.vue")['default'],
    'LazySharedNewFeedRightContent': typeof import("../components/shared/NewFeedRightContent.vue")['default'],
    'LazySharedSwiperContent': typeof import("../components/shared/SwiperContent.vue")['default'],
    'LazySvgBack': typeof import("../components/svg/Back.vue")['default'],
    'LazySvgBannerTrending': typeof import("../components/svg/BannerTrending.vue")['default'],
    'LazySvgComment': typeof import("../components/svg/Comment.vue")['default'],
    'LazySvgHeaderFilterBack': typeof import("../components/svg/HeaderFilterBack.vue")['default'],
    'LazySvgNotify': typeof import("../components/svg/Notify.vue")['default'],
    'LazySvgSearch': typeof import("../components/svg/Search.vue")['default'],
    'LazySvgSearchFilterHeader': typeof import("../components/svg/SearchFilterHeader.vue")['default'],
    'LazySvgSmile': typeof import("../components/svg/Smile.vue")['default'],
    'LazySvgStar': typeof import("../components/svg/Star.vue")['default'],
    'LazySvgView': typeof import("../components/svg/View.vue")['default'],
    'LazySvgViewChapter': typeof import("../components/svg/ViewChapter.vue")['default'],
    'LazySvgViewSpotLight': typeof import("../components/svg/ViewSpotLight.vue")['default'],
    'LazySvgFollow': typeof import("../components/svg/follow.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default'],
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-img.vue")['default'],
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-picture.vue")['default']
  }
}
export const NuxtLoadingBar: typeof import("../components/NuxtLoadingBar.vue")['default']
export const TheFooter: typeof import("../components/TheFooter.vue")['default']
export const TheHeader: typeof import("../components/TheHeader.vue")['default']
export const TheHome: typeof import("../components/TheHome.vue")['default']
export const TheMangaDetail: typeof import("../components/TheMangaDetail.vue")['default']
export const TheNav: typeof import("../components/TheNav.vue")['default']
export const TheRead: typeof import("../components/TheRead.vue")['default']
export const TheSidebar: typeof import("../components/TheSidebar.vue")['default']
export const VisitedComic: typeof import("../components/VisitedComic.vue")['default']
export const CategorysCateList: typeof import("../components/categorys/CateList.vue")['default']
export const CategorysComicItem: typeof import("../components/categorys/ComicItem.vue")['default']
export const CommonPageLoading: typeof import("../components/common/PageLoading.vue")['default']
export const CommonSearchLoading: typeof import("../components/common/SearchLoading.vue")['default']
export const HomePageCatelog: typeof import("../components/home-page/Catelog.vue")['default']
export const HomePageFavoriteStory: typeof import("../components/home-page/FavoriteStory.vue")['default']
export const HomePageMangaUpdated: typeof import("../components/home-page/MangaUpdated.vue")['default']
export const HomePageMaybeLove: typeof import("../components/home-page/MaybeLove.vue")['default']
export const HomePageNewFeed: typeof import("../components/home-page/NewFeed.vue")['default']
export const HomePageNewStory: typeof import("../components/home-page/NewStory.vue")['default']
export const HomePageRankList: typeof import("../components/home-page/RankList.vue")['default']
export const FilterByChapter: typeof import("../components/filter/ByChapter.vue")['default']
export const FilterByComics: typeof import("../components/filter/ByComics.vue")['default']
export const FilterByGender: typeof import("../components/filter/ByGender.vue")['default']
export const FilterByGenres: typeof import("../components/filter/ByGenres.vue")['default']
export const FilterByRank: typeof import("../components/filter/ByRank.vue")['default']
export const FilterByStatus: typeof import("../components/filter/ByStatus.vue")['default']
export const FilterListGenres: typeof import("../components/filter/ListGenres.vue")['default']
export const MangaChaplist: typeof import("../components/manga/Chaplist.vue")['default']
export const MangaChapterImg: typeof import("../components/manga/ChapterImg.vue")['default']
export const MangaReadMangaFooter: typeof import("../components/manga/ReadMangaFooter.vue")['default']
export const MangaReview: typeof import("../components/manga/Review.vue")['default']
export const MangaDetailFollowButton: typeof import("../components/manga-detail/FollowButton.vue")['default']
export const MangaDetailReadButton: typeof import("../components/manga-detail/ReadButton.vue")['default']
export const MangaDetailReview: typeof import("../components/manga-detail/Review.vue")['default']
export const ModalMangaSearch: typeof import("../components/modal/MangaSearch.vue")['default']
export const ModalSearchResult: typeof import("../components/modal/SearchResult.vue")['default']
export const PulseFavoriteStoryLoading: typeof import("../components/pulse/FavoriteStoryLoading.vue")['default']
export const PulseMangaUpdatedLoading: typeof import("../components/pulse/MangaUpdatedLoading.vue")['default']
export const PulseMaybeLoveLoading: typeof import("../components/pulse/MaybeLoveLoading.vue")['default']
export const PulseVisitedComic: typeof import("../components/pulse/VisitedComic.vue")['default']
export const SectionRankList: typeof import("../components/section/RankList.vue")['default']
export const SectionSpotlight: typeof import("../components/section/Spotlight.vue")['default']
export const SectionSpotlightBannerLoading: typeof import("../components/section/SpotlightBannerLoading.vue")['default']
export const SectionSuggestion: typeof import("../components/section/Suggestion.vue")['default']
export const SectionSwiperBannerLoading: typeof import("../components/section/SwiperBannerLoading.vue")['default']
export const SectionSwiperCard: typeof import("../components/section/SwiperCard.vue")['default']
export const SectionSwiperCardButton: typeof import("../components/section/SwiperCardButton.vue")['default']
export const SectionSwiperItemLoading: typeof import("../components/section/SwiperItemLoading.vue")['default']
export const SharedBannerBar: typeof import("../components/shared/BannerBar.vue")['default']
export const SharedImg: typeof import("../components/shared/Img.vue")['default']
export const SharedNewFeedLeftContent: typeof import("../components/shared/NewFeedLeftContent.vue")['default']
export const SharedNewFeedRightContent: typeof import("../components/shared/NewFeedRightContent.vue")['default']
export const SharedSwiperContent: typeof import("../components/shared/SwiperContent.vue")['default']
export const SvgBack: typeof import("../components/svg/Back.vue")['default']
export const SvgBannerTrending: typeof import("../components/svg/BannerTrending.vue")['default']
export const SvgComment: typeof import("../components/svg/Comment.vue")['default']
export const SvgHeaderFilterBack: typeof import("../components/svg/HeaderFilterBack.vue")['default']
export const SvgNotify: typeof import("../components/svg/Notify.vue")['default']
export const SvgSearch: typeof import("../components/svg/Search.vue")['default']
export const SvgSearchFilterHeader: typeof import("../components/svg/SearchFilterHeader.vue")['default']
export const SvgSmile: typeof import("../components/svg/Smile.vue")['default']
export const SvgStar: typeof import("../components/svg/Star.vue")['default']
export const SvgView: typeof import("../components/svg/View.vue")['default']
export const SvgViewChapter: typeof import("../components/svg/ViewChapter.vue")['default']
export const SvgViewSpotLight: typeof import("../components/svg/ViewSpotLight.vue")['default']
export const SvgFollow: typeof import("../components/svg/follow.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-img.vue")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-picture.vue")['default']
export const LazyNuxtLoadingBar: typeof import("../components/NuxtLoadingBar.vue")['default']
export const LazyTheFooter: typeof import("../components/TheFooter.vue")['default']
export const LazyTheHeader: typeof import("../components/TheHeader.vue")['default']
export const LazyTheHome: typeof import("../components/TheHome.vue")['default']
export const LazyTheMangaDetail: typeof import("../components/TheMangaDetail.vue")['default']
export const LazyTheNav: typeof import("../components/TheNav.vue")['default']
export const LazyTheRead: typeof import("../components/TheRead.vue")['default']
export const LazyTheSidebar: typeof import("../components/TheSidebar.vue")['default']
export const LazyVisitedComic: typeof import("../components/VisitedComic.vue")['default']
export const LazyCategorysCateList: typeof import("../components/categorys/CateList.vue")['default']
export const LazyCategorysComicItem: typeof import("../components/categorys/ComicItem.vue")['default']
export const LazyCommonPageLoading: typeof import("../components/common/PageLoading.vue")['default']
export const LazyCommonSearchLoading: typeof import("../components/common/SearchLoading.vue")['default']
export const LazyHomePageCatelog: typeof import("../components/home-page/Catelog.vue")['default']
export const LazyHomePageFavoriteStory: typeof import("../components/home-page/FavoriteStory.vue")['default']
export const LazyHomePageMangaUpdated: typeof import("../components/home-page/MangaUpdated.vue")['default']
export const LazyHomePageMaybeLove: typeof import("../components/home-page/MaybeLove.vue")['default']
export const LazyHomePageNewFeed: typeof import("../components/home-page/NewFeed.vue")['default']
export const LazyHomePageNewStory: typeof import("../components/home-page/NewStory.vue")['default']
export const LazyHomePageRankList: typeof import("../components/home-page/RankList.vue")['default']
export const LazyFilterByChapter: typeof import("../components/filter/ByChapter.vue")['default']
export const LazyFilterByComics: typeof import("../components/filter/ByComics.vue")['default']
export const LazyFilterByGender: typeof import("../components/filter/ByGender.vue")['default']
export const LazyFilterByGenres: typeof import("../components/filter/ByGenres.vue")['default']
export const LazyFilterByRank: typeof import("../components/filter/ByRank.vue")['default']
export const LazyFilterByStatus: typeof import("../components/filter/ByStatus.vue")['default']
export const LazyFilterListGenres: typeof import("../components/filter/ListGenres.vue")['default']
export const LazyMangaChaplist: typeof import("../components/manga/Chaplist.vue")['default']
export const LazyMangaChapterImg: typeof import("../components/manga/ChapterImg.vue")['default']
export const LazyMangaReadMangaFooter: typeof import("../components/manga/ReadMangaFooter.vue")['default']
export const LazyMangaReview: typeof import("../components/manga/Review.vue")['default']
export const LazyMangaDetailFollowButton: typeof import("../components/manga-detail/FollowButton.vue")['default']
export const LazyMangaDetailReadButton: typeof import("../components/manga-detail/ReadButton.vue")['default']
export const LazyMangaDetailReview: typeof import("../components/manga-detail/Review.vue")['default']
export const LazyModalMangaSearch: typeof import("../components/modal/MangaSearch.vue")['default']
export const LazyModalSearchResult: typeof import("../components/modal/SearchResult.vue")['default']
export const LazyPulseFavoriteStoryLoading: typeof import("../components/pulse/FavoriteStoryLoading.vue")['default']
export const LazyPulseMangaUpdatedLoading: typeof import("../components/pulse/MangaUpdatedLoading.vue")['default']
export const LazyPulseMaybeLoveLoading: typeof import("../components/pulse/MaybeLoveLoading.vue")['default']
export const LazyPulseVisitedComic: typeof import("../components/pulse/VisitedComic.vue")['default']
export const LazySectionRankList: typeof import("../components/section/RankList.vue")['default']
export const LazySectionSpotlight: typeof import("../components/section/Spotlight.vue")['default']
export const LazySectionSpotlightBannerLoading: typeof import("../components/section/SpotlightBannerLoading.vue")['default']
export const LazySectionSuggestion: typeof import("../components/section/Suggestion.vue")['default']
export const LazySectionSwiperBannerLoading: typeof import("../components/section/SwiperBannerLoading.vue")['default']
export const LazySectionSwiperCard: typeof import("../components/section/SwiperCard.vue")['default']
export const LazySectionSwiperCardButton: typeof import("../components/section/SwiperCardButton.vue")['default']
export const LazySectionSwiperItemLoading: typeof import("../components/section/SwiperItemLoading.vue")['default']
export const LazySharedBannerBar: typeof import("../components/shared/BannerBar.vue")['default']
export const LazySharedImg: typeof import("../components/shared/Img.vue")['default']
export const LazySharedNewFeedLeftContent: typeof import("../components/shared/NewFeedLeftContent.vue")['default']
export const LazySharedNewFeedRightContent: typeof import("../components/shared/NewFeedRightContent.vue")['default']
export const LazySharedSwiperContent: typeof import("../components/shared/SwiperContent.vue")['default']
export const LazySvgBack: typeof import("../components/svg/Back.vue")['default']
export const LazySvgBannerTrending: typeof import("../components/svg/BannerTrending.vue")['default']
export const LazySvgComment: typeof import("../components/svg/Comment.vue")['default']
export const LazySvgHeaderFilterBack: typeof import("../components/svg/HeaderFilterBack.vue")['default']
export const LazySvgNotify: typeof import("../components/svg/Notify.vue")['default']
export const LazySvgSearch: typeof import("../components/svg/Search.vue")['default']
export const LazySvgSearchFilterHeader: typeof import("../components/svg/SearchFilterHeader.vue")['default']
export const LazySvgSmile: typeof import("../components/svg/Smile.vue")['default']
export const LazySvgStar: typeof import("../components/svg/Star.vue")['default']
export const LazySvgView: typeof import("../components/svg/View.vue")['default']
export const LazySvgViewChapter: typeof import("../components/svg/ViewChapter.vue")['default']
export const LazySvgViewSpotLight: typeof import("../components/svg/ViewSpotLight.vue")['default']
export const LazySvgFollow: typeof import("../components/svg/follow.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-img.vue")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-picture.vue")['default']
export const componentNames: string[]
